### ISSUE TITLE
How can I define the global name 'FeatureExtractor'?

### ISSUE THREAD

**Issue by Sally-fyk** [vsubhashini/noc#7]
I'm sorry to bother you, but I'm really confused about this.
 As I'm trying to run the noc_captioner.py, there is an error:

`Setting up CNN...
Traceback (most recent call last):
  File "noc_captioner.py", line 571, in <module>
    main()
  File "noc_captioner.py", line 511, in main
    feature_extractor = FeatureExtractor(args.vggmodel, VGG_NET_FILE, DEVICE_ID)
NameError: global name 'FeatureExtractor' is not defined
`
Am I lost something necessary for the captioner? How can I fix it? I really appreciate if you can help me.

**Comment by vsubhashini** [comment]
Thanks, was it not imported correctly?

**Comment by Sally-fyk** [comment]
Thanks for response. I've already fix that. I'm wondering how did you evaluate the F1 score for your captioner? Could you please provide the code? Thank you so much! 

> 在 2018年4月9日，22:38，vsubhashini <notifications@github.com> 写道：
> 
> Thanks, was it not imported correctly?
>

**Comment by vsubhashini** [comment]
We computed F1 by first computing precision and recall on individual mentions of the object name in the sentence. I used the evaluation from DCC: https://github.com/LisaAnne/DCC.

**Comment by vsubhashini** [comment]
Look at score_dcc here:
https://github.com/LisaAnne/sentence_gen_tools/blob/master/coco_eval.py#L90

Use it the following way:

gt_template_novel = coco_annotations +
'captions_split_set_%s_%s_novel2014.json'
gt_template_train = coco_annotations +
'captions_split_set_%s_%s_train2014.json'
new_words = ['bus', 'bottle', 'couch', 'microwave', 'pizza', 'racket',
'suitcase', 'zebra'] score_dcc(gt_template_novel, gt_template_train,
save_caps, new_words, split) #split is val or test

**Comment by Sally-fyk** [comment]
Hello! I'm a student and I chose to study your paper"Captioning Images with Diverse Objects"as my undergraduate gradution design . I'm a beginner of machine learning and got a lot of problems while trying to reproduce your experiment.


First, in the code to generate.h5 file , it requires files such as 
POOLFEAT_FILE_PATTERN = 'data/coco2014/coco2014_{0}_vgg_fc7.txt'
SENTS_FILE_PATTERN = 'data/coco2014/sents/coco_sentences_{0}_tokens.txt'
LABEL_FILE_PATTERN = 'data/coco2014/sents/labels_glove72k_{0}.txt' #train2014
IMAGEID_FILE_PATTERN = 'data/coco2014/cvpr17_rm8newobjs/coco_rm8newobjs_image_list_{0}.txt'
I managed to create it by myself, but got many errors because the format is wrong.


Second, while I'm trying to evaluate the F1-score , I can't get the groundtruth references.txt of MSCOCO captions. And to evaluate the METEOR-score, there is something wrong to generate the
gt_template_novel = coco_annotations + 'captions_split_set_%s_%s_novel2014.json'

gt_template_train = coco_annotations + 'captions_split_set_%s_%s_train2014.json'



It's really hard for me to figure out these files. I can't find any help from others and I must finish it in a short time, so I come to ask you for help. Would you please send these files to me by email? I will really appreciate you.
